TK1/apps/main/urls.py
from django.urls import path
from .views import home, add_tips, remove_tips, add_news, remove_news, news, tips
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('news/', news, name='news'),
    path('tips/', tips, name='tips'),
    path('add-tips/', add_tips, name='add_tips'),
    path('remove-tips/<int:id>', remove_tips, name='remove_tips'),
    path('add-news/', add_news, name='add_news'),
    path('remove-news/<int:id>', remove_news, name='remove_news'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

TK1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TK1.apps.main.urls')),
    path('account/', include('TK1.apps.teofanus.urls')),
    path('rapid-test/', include('TK1.apps.nadia.urls')),
]

TK1/apps/main/models.py
from django.db import models

# Create your models here.

class News(models.Model):
    title = models.CharField(max_length=150)
    link = models.CharField(max_length=256)
    image_headline = models.CharField(max_length=256)

    class Meta:
        verbose_name = 'news'
        verbose_name_plural = 'news'

    def __str__(self) -> str:self.title

class Tips(models.Model):
    title = models.CharField(max_length=128)
    description = models.CharField(max_length=256)
    image = models.ImageField(null=True, blank=True, upload_to="tips_images/")

    class Meta:
        verbose_name = 'tip'
        verbose_name_plural = 'tips'

    def __str__(self) -> str:self.title

TK1/apps/main/forms.py
from django.forms import ModelForm
from .models import News, Tips

class NewsForm(ModelForm):
    class Meta:
        model = News
        fields = '__all__'

class TipsForm(ModelForm):
    class Meta:
        model = Tips
        fields = '__all__'

TK1/apps/main/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import News, Tips
from .forms import NewsForm, TipsForm
from django.contrib import messages

def home(request):
    news = News.objects.all()
    tips = Tips.objects.all()
    response = {'confirmed_case': '361,867', 'active_case': '64,032', 'recovered': '258,324', 'dead': '12,511', 'news': news, 'tips': tips}
    return render(request, 'main/home.html', response)

def news(request):
    form = NewsForm(request.POST or None)
    response = {'form': form}
    return render(request, 'main/news.html', response)

def tips(request):
    form = TipsForm(request.POST or None)
    response = {'form': form}
    return render(request, 'main/tips.html', response)

def add_tips(request):
    if request.method == 'POST':
        form = TipsForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Tips added successfully!")
            return redirect('main:home')
        else:
            messages.error(request, "The uploaded file must be an image!")
            return redirect('main:tips')
    form = TipsForm()
    response = {'form': form}
    return render(request, 'main/home.html', response)

def remove_tips(request, id):
    tips = get_object_or_404(Tips, pk=id)
    tips.delete()
    messages.success(request, "Tips has been deleted")
    return redirect('main:home')

def add_news(request):
    form = NewsForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, "News added successfully!")
        return redirect('main:home')
    response = {'form': form}
    return render(request, 'main/home.html', response)

def remove_news(request, id):
    news = get_object_or_404(News, pk=id)
    news.delete()
    messages.success(request, "News has been deleted")
    return redirect('main:home')

TK1/apps/main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<link href="{% static 'main/css/index.css' %}" rel="stylesheet">
<title>Hello!</title>
{% endblock meta %}

{% block content %}
{% if messages %}
    {% for message in messages %}
        <div{% if message.tags %} class="{{ message.tags }}" {% endif %}>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
{% if register_form.errors %}
    {% for field in register_form %}
        {% for error in field.errors %}
            <div class="error">
                {{ error|escape }} 
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in register_form.non_field_errors %}
        <div class="error">
            {{ error|escape }}
        </div>
    {% endfor %}
{% endif %}
<section class="relative bg-auto bg-contain bg-right-bottom bg-no-repeat px-16 pt-8">
  <header class="text-4xl lg:text-6xl font-bold">
    <h1>Save yourself</h1>
    <h1>Save the world</h1>
  </header>
  <p class="text-md lg:text-xl lg:w-3/4 pt-6">Cara terbaik untuk mencegah dan memperlambat penularan adalah dengan mengetahui dengan baik tentang virus, penyakit yang ditimbulkannya dan bagaimana penyebarannya.</p>
  <svg width="283" height="189" viewBox="0 0 343 249" fill="none" xmlns="http://www.w3.org/2000/svg" class="absolute top-0 left-0" style="z-index: -1;">
      <path d="M343 -21C343 128.117 222.117 249 73 249C-76.1169 249 -197 128.117 -197 -21C-197 -170.117 -76.1169 -291 73 -291C222.117 -291 343 -170.117 343 -21Z" fill="#BFD1FF"/>
  </svg>
  <svg width="250" height="105" viewBox="0 0 290 145" fill="none" xmlns="http://www.w3.org/2000/svg" class="absolute left-0 bottom-0 pl-12" style="z-index: -1;">
      <path d="M0 145C0 125.958 3.75054 107.103 11.0375 89.5109C18.3244 71.9187 29.005 55.934 42.4695 42.4695C55.934 29.005 71.9187 18.3244 89.5109 11.0375C107.103 3.75053 125.958 -8.32338e-07 145 0C164.042 8.32338e-07 182.897 3.75054 200.489 11.0375C218.081 18.3244 234.066 29.005 247.53 42.4695C260.995 55.934 271.676 71.9187 278.963 89.5109C286.249 107.103 290 125.958 290 145L145 145L0 145Z" fill="#BFD1FF"/>
  </svg>
  <div style="height: 6rem;"></div>
  <img src="../../static/main/images/doctor.png" alt="Test" class="hidden md:block max-w-lg absolute right-0 bottom-0 pr-16" style="z-index: -1;">
</section>

<section class="mx-8 my-4 flex flex-row flex-wrap justify-center">
  <div class="flex flex-row flex-wrap items-center rounded-2xl mb-4 p-4 justify-center max-w-3xl text-center gap-x-2" style="background-color: #F3F1FF;">
    <div>
      <header class="text-2xl">{{ confirmed_case }}</header>
      <p class="font-bold text-sm md:text-lg">Terkonfirmasi</p>
    </div>
    <div class="h-16 border-solid border-black border-l-2"></div>
    <div>
      <header class="text-2xl" style="color: var(--yellow);">{{ active_case }}</header>
      <p class="font-bold text-sm md:text-lg">Kasus Aktif</p>
    </div>
    <div class="h-16 border-solid border-black border-l-2"></div>
    <div>
      <header class="text-2xl" style="color: var(--green);">{{ recovered }}</header>
      <p class="font-bold text-sm md:text-lg">Sembuh</p>
    </div>
    <div class="h-16 border-solid border-black border-l-2"></div>
    <div>
      <header class="text-2xl" style="color: var(--red);">{{ dead }}</header>
      <p class="font-bold text-sm md:text-lg">Meninggal</p>
    </div>
  </div>
</section>

<section class="flex flex-col mx-8 my-4 gap-4 mb-4 items-center">
  <div class="rounded-2xl p-4 flex flex-col md:flex-row align-center gap-x-4 justify-center w-3/5 shadow-xl" style="background-color: #D8E7FF;">
    <div>
      <header class="text-2xl font-bold">Mulai Asesmen!</header>
      <p class="mb-4">Ikuti asesmen untuk mengetahui kondisimu</p>
      <div class="inline-block rounded-2xl px-6 py-1 text-white text-center" style="background-color: var(--blue-dark);">
        <a href="" class="text-white text-center">Mulai Asesmen</a>
      </div>
    </div>
    <img src="{% static 'main/images/virus.png' %}" alt="Medical Report Image" class="h-32 w-auto hidden md:block">
    <img src="{% static 'main/images/virus.png' %}" alt="Medical Report Image" class="h-32 w-auto transform -rotate-45 hidden lg:block">
  </div>
  
  <div class="rounded-2xl p-4 flex flex-col md:flex-row justify-center gap-x-4 w-3/5 shadow-xl" style="background-color: #ADCEFF;">
    <img src="{% static 'main/images/medical-report.png' %}" alt="Medical Report Image" class="h-auto w-auto hidden md:block">
    <div>
      <header class="text-2xl font-bold">Kunjungi Lokasi Rapid Test</header>
      <p class="mb-4">Dapatkan informasi  mengenai lokasi Rapid Test terdekat</p>
      <div class="inline-block rounded-2xl px-6 py-1 text-center" style="background-color: var(--blue-dark);">
        <a href="" class="text-white">Lokasi Rapid Test</a>
      </div>
    </div>
  </div>
</section>

<!-- flex flex-col md:flex md:flex-row -->

<section class="mx-8 mb-4">
  <header class="font-bold text-2xl mb-4">Berita seputar COVID-19</header>
  <div class="grid grid-flow-row sm:grid-cols-2 md:grid-cols-3 gap-4 items-center md:justify-center px-4 md:px-16 items-stretch">
    <div class="border-solid border-2 rounded-lg overflow-hidden">
      <a href="https://www.voaindonesia.com/a/efektivitas-vaksin-covid-19-eksperimental-modena-lebih-dari-90-persen/5664646.html" target="_blank" rel="noopener noreferrer">
        <img src="https://gdb.voanews.com/7DDA3B9A-A0E2-4E2A-9B32-057273B75E11_cx0_cy3_cw0_w1023_r1_s.jpg" alt="Botol dengan stiker bertuliskan, 'COVID-19 / vaksin Coronavirus / hanya untuk injeksi' dan jarum suntik terlihat di depan logo Moderna, 31 Oktober 2020. (REUTERS / Dado Ruvic / Ilustrasi)" class="w-full">
      </a>
      <header class="px-6 pt-4">Efektivitas Vaksin COVID-19 Eksperimental Moderna Lebih dari 94 Persen</header>
    </div>
    <div class="border-solid border-2 rounded-lg overflow-hidden">
      <a href="https://palu.tribunnews.com/2020/11/17/dirjen-who-vaksin-saja-tidak-cukup-untuk-menghentikan-pandemi-covid-19" target="_blank" rel="noopener noreferrer">
        <img src="https://cdn-2.tstatic.net/palu/foto/bank/images/tedros.jpg" alt="'Vaksin saja tidak akan mengakhiri pandemi Covid-19,'' kata Direktur Jenderal WHO Tedros Adhanom Ghebreyesus pada Senin (16/11/2020)" alt="Ilustrasi tes Covid-19, deteksi Covid-19, pengujian virus corona" class="w-full">
      </a>
      <header class="px-6 pt-4">Dirjen WHO: Vaksin Saja Tidak Cukup untuk Menghentikan Pandemi Covid-19</header>
    </div>
    <div class="border-solid border-2 rounded-lg overflow-hidden">
      <a href="https://ternate.tribunnews.com/2020/11/17/breaking-news-tambah-3807-total-kasus-virus-corona-indonesia-jadi-474455-per-17-november-2020" target="_blank" rel="noopener noreferrer">
        <img src="https://cdn-2.tstatic.net/ternate/foto/bank/images/poster-ilustrasi-virus-corona-atau-covid-19.jpg" alt="Ilustrasi tes Covid-19, deteksi Covid-19, pengujian virus corona" class="w-full">
      </a>
      <header class="px-6 pt-4">BREAKING NEWS: Tambah 3.807, Total Kasus Virus Corona Indonesia Jadi 474.455 per 17 November 2020</header>
    </div>
    {% for each in news %}
      <div class="border-solid border-2 rounded-lg overflow-hidden">
        <a href="{{ each.link }}" target="_blank" rel="noopener noreferrer">
          <img src="{{ each.image_headline }}" class="w-full">
        </a>
        <header class="px-6 pt-4">{{ each.title }}</header>
        <div class="px-6 py-4 flex justify-center">
          <a href="{% url 'main:remove_news' each.id %}" class="bg-red-500 px-8 rounded-2xl">Delete</a>
        </div>
      </div>
    {% endfor %}
    <a href="{% url 'main:news' %}" class="flex flex-col items-center justify-center text-black text-center inline-block rounded-2xl">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>
      Add News
    </a>
  </div>
</section>

<section class="mx-8 mb-4">
  <header class="font-bold text-2xl mb-4">Pencegahan COVID-19</header>
  <div class="grid grid-flow-row sm:grid-cols-2 md:grid-cols-3 gap-4 px-4 md:px-16 pb-8">
    <div class="text-center flex flex-col items-center justify-center">
      <img src="{% static 'main/images/tips1.png' %}" alt="Tips 1" class="w-1/3 mb-4">
      <header class="font-bold mb-4">Menjaga kebersihan</header>
      <p>Mencuci tangan dengan rutin menggunakan sabun dan air atau pembersih tangan berbahan alcohol</p>
    </div>
    <div class="text-center flex flex-col items-center justify-center">
      <img src="{% static 'main/images/tips2.png' %}" alt="Tips 2" class="w-1/3 mb-4">
      <header class="font-bold mb-4">Menggunakan masker</header>
      <p>Menggunakan masker pada saat berpergian jika pembatasan fisik tidak memungkinkan</p>
    </div>
    <div class="text-center flex flex-col items-center justify-center">
      <img src="{% static 'main/images/tips3.png' %}" alt="Tips 3" class="w-1/3 mb-4">
      <header class="font-bold mb-4">Melakukan social distancing</header>
      <p>Selalu jaga jarak aman dengan orang lain terlebih dengan orang yang batuk atau bersin</p>
    </div>
    <div class="text-center flex flex-col items-center justify-center">
      <img src="{% static 'main/images/tips4.png' %}" alt="Tips 4" class="w-1/3 mb-4">
      <header class="font-bold mb-4">Tetap di dalam rumah</header>
      <p>Jika tidak ada kepentingan yang mendesak maka sangat dianjurkan untuk menetap dalam rumah</p>
    </div>
    <div class="text-center flex flex-col items-center justify-center">
      <img src="{% static 'main/images/tips5.png' %}" alt="Tips 5" class="w-1/3 mb-4">
      <header class="font-bold mb-4">Menghindari makanan setengah matang</header>
      <p>Memasak makanan sampai makanan tersebut benar-benar matang agar aman dikonsumsi</p>
    </div>
    <div class="text-center flex flex-col items-center justify-center">
      <img src="{% static 'main/images/tips6.png' %}" alt="Tips 6" class="w-1/3 mb-4">
      <header class="font-bold mb-4">Menjaga pola hidup sehat</header>
      <p>Melakukan olahraga rutin yang diimbangi dengan asupan gizi yang cukup agar tetap bugar</p>
    </div>
    {% for each in tips %}
      <div class="text-center flex flex-col items-center justify-center">
        {% if each.image %}
          <img src="{{ each.image.url }}" alt="Tips 1" class="w-1/3 mb-4 rounded-full">
        {% else %}
          <img src="{% static 'main/images/logo.svg' %}" alt="Tips 1" class="w-1/3 mb-4 rounded-full">
        {% endif %}
        <header class="font-bold mb-4">{{ each.title }}</header>
        <p>{{ each.description }}</p>
        <div class="px-6 pt-4 flex justify-center">
          <a href="{% url 'main:remove_tips' each.id %}" class="bg-red-500 px-8 rounded-2xl">Delete</a>
        </div>
      </div>
    {% endfor %}
    <a href="{% url 'main:tips' %}" class="flex flex-col items-center justify-center text-black text-center inline-block rounded-2xl">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>
      Add Tips
    </a>
  </div>
</section>

{% endblock content %}

TK1/apps/main/templates/main/news.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<link href="{% static 'main/css/index.css' %}" rel="stylesheet">
<title>Hello!</title>
{% endblock meta %}

{% block content %}
<section class="w-3/4 py-8 m-auto">
    {% if messages %}
        {% for message in messages %}
            <div{% if message.tags %} class="{{ message.tags }}" {% endif %}>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% if register_form.errors %}
        {% for field in register_form %}
            {% for error in field.errors %}
                <div class="error">
                    {{ error|escape }} 
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in register_form.non_field_errors %}
            <div class="error">
               {{ error|escape }}
            </div>
        {% endfor %}
    {% endif %}
    <header class="text-2xl text-center">Add News</header>
    <form action="{% url 'main:add_news' %}" method="POST">
        {% csrf_token %}
        <div class="frm rounded-lg">
            {{ form.title.label_tag }}
            {{ form.title }}
        </div>

        <div class="frm">
            {{ form.link.label_tag }}
            {{ form.link }}
        </div>

        <div class="frm">
            {{ form.image_headline.label_tag }}
            {{ form.image_headline }}
        </div>

        <div class="text-center">
            <input type="submit" value="Add" class="btn dark rounded-3xl py-2 px-6 focus:outline-none focus:border-blue-300 focus:shadow-outline">
        </div>
    </form>
</section>
{% endblock content %}

TK1/apps/main/templates/main/tips.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<link href="{% static 'main/css/index.css' %}" rel="stylesheet">
<title>Hello!</title>
{% endblock meta %}

{% block content %}
<section class="w-3/4 py-8 m-auto">
    {% if messages %}
        {% for message in messages %}
            <div{% if message.tags %} class="{{ message.tags }}" {% endif %}>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% if register_form.errors %}
        {% for field in register_form %}
            {% for error in field.errors %}
                <div class="error">
                    {{ error|escape }} 
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in register_form.non_field_errors %}
            <div class="error">
               {{ error|escape }}
            </div>
        {% endfor %}
    {% endif %}
    <header class="text-2xl text-center">Add Tips</header>
    <form action="{% url 'main:add_tips' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="frm">
            {{ form.title.label_tag }}
            {{ form.title }}
        </div>

        <div class="frm">
            {{ form.description.label_tag }}
            {{ form.description }}
        </div>

        <div class="frm">
            {{ form.image.label_tag }}
            {{ form.image }}
        </div>

        <div class="text-center">
            <input type="submit" value="Add" class="btn dark rounded-3xl py-2 px-6 focus:outline-none focus:border-blue-300 focus:shadow-outline">
        </div>
    </form>
</section>
{% endblock content %}