TK1/apps/main/urls.py
from django.urls import path
from .views import home, add_tips, remove_tips, add_news, remove_news, news, tips
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('news/', news, name='news'),
    path('tips/', tips, name='tips'),
    path('add-tips/', add_tips, name='add_tips'),
    path('remove-tips/<int:id>', remove_tips, name='remove_tips'),
    path('add-news/', add_news, name='add_news'),
    path('remove-news/<int:id>', remove_news, name='remove_news'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

TK1/apps/nadia/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
app_name = 'TK1.apps.nadia'

urlpatterns = [
    path('lokasiTest', views.lokasiTest, name='lokasiTest' ), 
]

TK1/apps/teofanus/urls.py
from django.urls import path

from .views import login, register, register_account, login_account, logout_account

app_name = "teofanus"

urlpatterns = [
    path('login/', login, name="login"),
    path('register/', register, name="register"),
    path('register_account/', register_account, name="register_account"),
    path('login_account/', login_account, name="login_account"),
    path('logout_account', logout_account, name="logout_account"),
]

TK1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TK1.apps.main.urls')),
    path('account/', include('TK1.apps.teofanus.urls')),
    path('rapid-test/', include('TK1.apps.nadia.urls')),
]

TK1/apps/linus/models.py
from django.db import models

# Create your models here.

TK1/apps/main/models.py
from django.db import models

# Create your models here.

class News(models.Model):
    title = models.CharField(max_length=150)
    link = models.CharField(max_length=256)
    image_headline = models.CharField(max_length=256)

    class Meta:
        verbose_name = 'news'
        verbose_name_plural = 'news'

    def __str__(self) -> str:self.title

class Tips(models.Model):
    title = models.CharField(max_length=128)
    description = models.CharField(max_length=256)
    image = models.ImageField(null=True, blank=True, upload_to="tips_images/")

    class Meta:
        verbose_name = 'tip'
        verbose_name_plural = 'tips'

    def __str__(self) -> str:self.title

TK1/apps/nadia/models.py
from django.db import models

# Create your models here.
class KotaModel(models.Model):
    nama_kota = models.CharField(max_length=100)
    def __str__(self):
        return self.nama_kota

class TempatModel(models.Model):
    nama_tempat = models.CharField(max_length=100)
    alamat = models.CharField(max_length=300, blank=True, null=True)
    gmaps = models.CharField(max_length=500, blank=True, null=True)
    deskripsi = models.TextField(max_length = 800)
    lokasi = models.ForeignKey(KotaModel, on_delete=models.CASCADE)
    def __str__(self):
        return self.nama_tempat

TK1/apps/patrick/models.py
from django.db import models

# Create your models here.

TK1/apps/teofanus/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class UserAccount(AbstractUser):
   email = models.EmailField(unique=True, verbose_name="Email")
   covid_result = models.CharField(max_length=20, verbose_name="Covid Result", null=True)
   test_taken = models.DateTimeField(verbose_name="Time and Date of Last COVID Test", null=True)

   REQUIRED_FIELDS = ['email', 'password']

   class Meta:
      verbose_name = 'user'
      verbose_name_plural = 'users'

TK1/apps/main/forms.py
from django.forms import ModelForm
from .models import News, Tips

class NewsForm(ModelForm):
    class Meta:
        model = News
        fields = '__all__'

class TipsForm(ModelForm):
    class Meta:
        model = Tips
        fields = '__all__'

TK1/apps/teofanus/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2']
    # def clean(self):
    #     email = self.cleaned_data.get('email')
    #     password = self.cleaned_data.get('password')

    #     if email is not None and password:
    #         self.user_cache = authenticate(self.request, email=email, password=password)
    #         if self.user_cache is None:
    #             raise self.get_invalid_login_error()
    #         else:
    #             self.confirm_login_allowed(self.user_cache)

    #     return self.cleaned_data

# class RegisterForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = '__all__'
#         labels = {
#             'name': 'Nama'
#         }
#         widgets = {
#             'password': forms.PasswordInput()
#         }


# class LoginForm(forms.ModelForm):
#     class Meta:
#         model = User
#         exclude = ['name']
#         widgets = {
#             'password': forms.PasswordInput()
#         }

TK1/apps/linus/views.py
from django.shortcuts import render

# Create your views here.

TK1/apps/main/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import News, Tips
from .forms import NewsForm, TipsForm
from django.contrib import messages

def home(request):
    news = News.objects.all()
    tips = Tips.objects.all()
    response = {'confirmed_case': '361,867', 'active_case': '64,032', 'recovered': '258,324', 'dead': '12,511', 'news': news, 'tips': tips}
    return render(request, 'main/home.html', response)

def news(request):
    form = NewsForm(request.POST or None)
    response = {'form': form}
    return render(request, 'main/news.html', response)

def tips(request):
    form = TipsForm(request.POST or None)
    response = {'form': form}
    return render(request, 'main/tips.html', response)

def add_tips(request):
    if request.method == 'POST':
        form = TipsForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Tips added successfully!")
            return redirect('main:home')
        else:
            messages.error(request, "The uploaded file must be an image!")
            return redirect('main:tips')
    form = TipsForm()
    response = {'form': form}
    return render(request, 'main/home.html', response)

def remove_tips(request, id):
    tips = get_object_or_404(Tips, pk=id)
    tips.delete()
    messages.success(request, "Tips has been deleted")
    return redirect('main:home')

def add_news(request):
    form = NewsForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, "News added successfully!")
        return redirect('main:home')
    response = {'form': form}
    return render(request, 'main/home.html', response)

def remove_news(request, id):
    news = get_object_or_404(News, pk=id)
    news.delete()
    messages.success(request, "News has been deleted")
    return redirect('main:home')

TK1/apps/nadia/views.py
from django.shortcuts import render, redirect 

from .models import KotaModel, TempatModel

# from .filters import KotaFilter

# Create your views here.

def lokasiTest(request):
    tempats = TempatModel.objects.all()
    if request.method == 'POST':
        query = request.POST['lokasi']
        tempats = tempats.filter(alamat__icontains=query)
        # context['query'] = query
        # context['allitems'] = allitems

    # myFilter = KotaFilter(request.GET, queryset = tempats)
    # tempats = myFilter.qs
    context = {
        'tempats': tempats,
        # 'myFilter': myFilter,
    }
    return render(request, "lokasiTest.html", context)

TK1/apps/patrick/views.py
from django.shortcuts import render

# Create your views here.

TK1/apps/teofanus/views.py
from django.shortcuts import redirect, render
from .forms import RegisterForm
from django.contrib.auth.forms import  AuthenticationForm
from django.contrib import messages
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as auth_login

# Create your views here.

def login(request):
    response = {'login_form': AuthenticationForm}
    return render(request, 'teofanus/login.html', response)

def register(request):
    response = {'register_form': RegisterForm}
    return render(request, 'teofanus/register.html', response)

def register_account(request):
    form = RegisterForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, "Account created successfully!")  
            return redirect('teofanus:register')
    response = {'register_form': form}
    return render(request, 'teofanus/register.html', response)

def login_account(request):
    form = AuthenticationForm(request.POST or None)
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username = username, password = password)
        
        if user is not None:
            auth_login(request, user)
            messages.success(request, "You have logged in successfully!")
            return redirect('teofanus:login')
        else:
            messages.error(
                request, "No account can be found, please check your credentials or register first if you have not done so")
            return redirect('teofanus:login')
    response = {'login_form': form}
    return render(request, 'teofanus/login.html', response)

def logout_account(request):
    logout(request)
    return redirect('main:home')

TK1/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  {% block meta %}
  <!-- Title Tag -->
  {% endblock meta %}
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;600&display=swap" rel="stylesheet">

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="https://unpkg.com/tailwindcss@^1/dist/tailwind.min.css" rel="stylesheet">

  <!-- Favicon
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="icon" type="image/png" href="{% static 'main/images/logo.svg' %}">

</head>

<body>
  <!-- NavBar
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <nav class="py-6 pr-12 flex md:flex-row flex-col md:items-center">
    <button onclick="toggleMenu()" class="md:hidden self-end px-3 py-2 border rounded border-black focus:outline-none focus:shadow-outline">
      <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
    <div class="md:flex items-center gap-x-4 pl-8" id="mobileMenu">
      <a href="{% url 'main:home' %}" class="block md:inline-block md:mt-0">Home</a>
      <a href="" class="block mt-4 md:inline-block md:mt-0">Statistik</a>
      <a href="{% url 'TK1.apps.nadia:lokasiTest' %}" class="block mt-4 md:inline-block md:mt-0">Rapid Test</a>
      <a href="" class="block mt-4 md:inline-block md:mt-0">Assesment</a>
      <div id="user" class="mt-4 block md:mt-0 mr-4 flex gap-x-2 justify-center">
        {% if user.is_authenticated %}
          <p>Hello {{ user.username }}!</p>
          <b>/</b>
          <a href="{% url 'teofanus:logout_account' %}">Logout</a>
        {% else %}
          <a href="{% url 'teofanus:register' %}">Register</a>
          <b>/</b>
          <a href="{% url 'teofanus:login' %}">Login</a>
        {% endif %}
      </div>
    </div>
  </nav>

  <script>
    function toggleMenu(){
      let mobileMenu = document.getElementById('mobileMenu');
      if (mobileMenu.classList.contains('hidden')) {
        mobileMenu.classList.remove('hidden')
      } else {
        mobileMenu.classList.add('hidden');
      }
    }
  </script>

  <!-- Primary Page Layout
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <div id="content">
    {% block content %}
    {% endblock content %}
  </div>

  <!-- Footer
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <footer>
    <p>Created with 💖 By kelompok B14</p>
  </footer>

<!-- End Document
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
</body>
</html>