TK1/apps/teofanus/urls.py
from django.urls import path

from .views import login, register, register_account, login_account, logout_account

app_name = "teofanus"

urlpatterns = [
    path('login/', login, name="login"),
    path('register/', register, name="register"),
    path('register_account/', register_account, name="register_account"),
    path('login_account/', login_account, name="login_account"),
    path('logout_account', logout_account, name="logout_account"),
]

TK1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TK1.apps.main.urls')),
    path('account/', include('TK1.apps.teofanus.urls')),
    path('rapid-test/', include('TK1.apps.nadia.urls')),
]

TK1/apps/teofanus/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class UserAccount(AbstractUser):
   email = models.EmailField(unique=True, verbose_name="Email")
   covid_result = models.CharField(max_length=20, verbose_name="Covid Result", null=True)
   test_taken = models.DateTimeField(verbose_name="Time and Date of Last COVID Test", null=True)

   REQUIRED_FIELDS = ['email', 'password']

   class Meta:
      verbose_name = 'user'
      verbose_name_plural = 'users'

TK1/apps/teofanus/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2']
    # def clean(self):
    #     email = self.cleaned_data.get('email')
    #     password = self.cleaned_data.get('password')

    #     if email is not None and password:
    #         self.user_cache = authenticate(self.request, email=email, password=password)
    #         if self.user_cache is None:
    #             raise self.get_invalid_login_error()
    #         else:
    #             self.confirm_login_allowed(self.user_cache)

    #     return self.cleaned_data

# class RegisterForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = '__all__'
#         labels = {
#             'name': 'Nama'
#         }
#         widgets = {
#             'password': forms.PasswordInput()
#         }


# class LoginForm(forms.ModelForm):
#     class Meta:
#         model = User
#         exclude = ['name']
#         widgets = {
#             'password': forms.PasswordInput()
#         }

TK1/apps/teofanus/views.py
from django.shortcuts import redirect, render
from .forms import RegisterForm
from django.contrib.auth.forms import  AuthenticationForm
from django.contrib import messages
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as auth_login

# Create your views here.

def login(request):
    response = {'login_form': AuthenticationForm}
    return render(request, 'teofanus/login.html', response)

def register(request):
    response = {'register_form': RegisterForm}
    return render(request, 'teofanus/register.html', response)

def register_account(request):
    form = RegisterForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, "Account created successfully!")  
            return redirect('teofanus:register')
    response = {'register_form': form}
    return render(request, 'teofanus/register.html', response)

def login_account(request):
    form = AuthenticationForm(request.POST or None)
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username = username, password = password)
        
        if user is not None:
            auth_login(request, user)
            messages.success(request, "You have logged in successfully!")
            return redirect('teofanus:login')
        else:
            messages.error(
                request, "No account can be found, please check your credentials or register first if you have not done so")
            return redirect('teofanus:login')
    response = {'login_form': form}
    return render(request, 'teofanus/login.html', response)

def logout_account(request):
    logout(request)
    return redirect('main:home')

TK1/apps/teofanus/templates/teofanus/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
<link href="{% static 'teofanus/css/index.css' %}" rel="stylesheet">
<title>Login</title>
{% endblock meta %}

{% block content %}
<section class="text-white">
    {% if messages %}
        {% for message in messages %}
            <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% if register_form.errors %}
        {% for field in register_form %}
            {% for error in field.errors %}
                <div class="error">
                    {{ error|escape }} 
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in register_form.non_field_errors %}
            <div class="error">
               {{ error|escape }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="flex flex-col md:flex-row mx-8 md:mx-16 mb-8">
        <div class="light rounded-t-xl md:rounded-tr-none md:rounded-bl-xl flex flex-col gap-2 md:w-2/3 h-auto">
            <header class="text-5xl pt-12 text-center">Masuk</header>
            <form action="{% url 'teofanus:login_account' %}" method="post" class="py-12 px-8 md:px-16">
                {% csrf_token %}
                <div class="frm">
                    {{ login_form.username.label_tag }}
                    <div class="flex">
                        <div class="rounded-l-lg" style="background-color: var(--gray);">
                            <img src="{% static 'teofanus/images/mail.svg' %}" halt="Lock Icon" class="py-4 pl-4 w-10">
                        </div>
                        {{ login_form.username }}
                    </div>
                </div>

                <div class="frm">
                    {{ login_form.password.label_tag }}
                    <div class="flex">
                        <div class="rounded-l-lg" style="background-color: var(--gray);">
                            <img src="{% static 'teofanus/images/lock.svg' %}" alt="Lock Icon" class="py-4 pl-4 w-10">
                        </div>
                        {{ login_form.password }}
                    </div>
                </div>

                <div class="text-center">
                    <input type="submit" value="Masuk" class="btn dark rounded-3xl py-2 px-6 focus:outline-none focus:border-blue-300 focus:shadow-outline">
                </div>
            </form>
        </div>
        <div class="dark rounded-b-xl md:rounded-bl-none md:rounded-tr-xl flex flex-col gap-2 text-center justify-center py-8 md:py-48 md:w-1/3">
            <p class="text-4xl">Halo!</p>
            <p>Belum pernah mendaftar?</p>
            <a href="{% url 'teofanus:register' %}">
                <button class="light rounded-3xl px-6 py-2 focus:outline-none focus:border-blue-300 focus:shadow-outline">
                    Daftar
                </button>
            </a>
        </div>
    </div>
</section>
{% endblock content %}

TK1/apps/teofanus/templates/teofanus/register.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
<link href="{% static 'teofanus/css/index.css' %}" rel="stylesheet">
<title>Register</title>
{% endblock meta %}

{% block content %}
<section class="text-white">
    {% if messages %}
        {% for message in messages %}
            <div{% if message.tags %} class="{{ message.tags }}" {% endif %}>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% if register_form.errors %}
        {% for field in register_form %}
            {% for error in field.errors %}
                <div class="error">
                    {{ error|escape }} 
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in register_form.non_field_errors %}
            <div class="error">
               {{ error|escape }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="flex flex-col md:flex-row mx-8 md:mx-16 mb-8">
        <div class="dark flex flex-col gap-2 rounded-t-xl md:rounded-tr-none md:rounded-bl-xl text-center justify-center py-8 md:py-48 md:w-1/3">
            <p class="text-4xl">Halo!</p>
            <p>Sudah pernah mendaftar?</p>
            <a href="{% url 'teofanus:login' %}">
                <button class="light rounded-3xl px-6 py-2 focus:outline-none focus:border-blue-300 focus:shadow-outline">
                    Masuk
                </button>
            </a>
        </div>
        <div class="light flex flex-col gap-2 rounded-b-xl md:rounded-bl-none md:rounded-tr-xl md:w-2/3 h-auto">
            <header class="text-5xl pt-12 text-center">Daftar Akun</header>
             <form action="{% url 'teofanus:register_account' %}" method="post" class="py-12 px-8 md:px-16">
                {% csrf_token %}
                <div class="frm">
                    {{ register_form.username.label_tag }}
                    <div class="flex">
                        <div class="rounded-l-lg" style="background-color: var(--gray);">
                            <img src="{% static 'teofanus/images/user.svg' %}" alt="Lock Icon" class="py-4 pl-4 w-10">
                        </div>
                        {{ register_form.username }}
                    </div>
                </div>

                <div class="frm">
                    {{ register_form.email.label_tag }}
                    <div class="flex">
                        <div class="rounded-l-lg" style="background-color: var(--gray);">
                            <img src="{% static 'teofanus/images/mail.svg' %}" alt="Lock Icon" class="py-4 pl-4 w-10">
                        </div>
                        {{ register_form.email }}
                    </div>
                </div>

                <div class="frm">
                    {{ register_form.password1.label_tag }}
                    <div class="flex">
                        <div class="rounded-l-lg" style="background-color: var(--gray);">
                            <img src="{% static 'teofanus/images/lock.svg' %}" alt="Lock Icon" class="py-4 pl-4 w-10">
                        </div>
                        {{ register_form.password1 }}
                    </div>
                </div>

                <div class="frm">
                    {{ register_form.password2.label_tag }}
                    <div class="flex">
                        <div class="rounded-l-lg" style="background-color: var(--gray);">
                            <img src="{% static 'teofanus/images/lock.svg' %}" alt="Lock Icon" class="py-4 pl-4 w-10">
                        </div>
                        {{ register_form.password2 }}
                    </div>
                </div>

                <div class="text-center">
                    <input type="submit" value="Daftar" class="btn dark rounded-3xl py-2 px-6 focus:outline-none focus:border-blue-300 focus:shadow-outline">
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock content %}